

services:
  prometheus:
    image: prom/prometheus
    container_name: llm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: llm-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  postgres:
    image: postgres:16
    container_name: llm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: llm_platform
      POSTGRES_USER: llm_user
      POSTGRES_PASSWORD: llm_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: llm-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: llm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    container_name: llm-kafka
    restart: unless-stopped
    ports:
      - "19092:9092"
    environment:
      # --- KRaft mode ---
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@llm-kafka:9093

      # --- Listeners ---
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # --- Single-node dev settings ---
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  postgres_data:
  mongo_data:

